# Generated by Django 4.2.11 on 2024-03-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_alter_location_options_alter_barter_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('location',)},
        ),
    ]
