# Generated by Django 4.2.11 on 2024-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0004_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barter_images'),
        ),
    ]
