# Generated by Django 4.2.11 on 2024-03-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0005_alter_barter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='exchange_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_barters', to='barter.barter'),
        ),
    ]
